version: 2
updates:
- package-ecosystem: nuget
  directories:
    - "src/Pure.Primitives.Abstractions.OpenAPI.Schema"
    - "src/Tests/Pure.Primitives.Abstractions.OpenAPI.Schema.Tests"
  schedule:
    interval: daily
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: weekly
