using Microsoft.AspNetCore.OpenApi;
using Microsoft.OpenApi;

namespace Pure.Primitives.Abstractions.OpenAPI.Schema;

public sealed class PrimitivesDocumentTransformer : IOpenApiDocumentTransformer
{
    // Maps schema component names (generated by ASP.NET Core OpenAPI) to native OpenAPI type schemas.
    // Pure.Primitives.Abstractions interfaces are schema-replaced so API consumers see primitive types.
    private static readonly IReadOnlyDictionary<string, OpenApiSchema> PrimitiveSchemas =
        new Dictionary<string, OpenApiSchema>(StringComparer.Ordinal)
        {
            ["IString"] = new() { Type = JsonSchemaType.String },
            ["IBool"] = new() { Type = JsonSchemaType.Boolean },
            ["IGuid"] = new() { Type = JsonSchemaType.String, Format = "uuid" },
            ["IChar"] = new() { Type = JsonSchemaType.String, MaxLength = 1 },
            ["IDate"] = new() { Type = JsonSchemaType.String, Format = "date" },
            ["ITime"] = new() { Type = JsonSchemaType.String, Format = "time" },
            ["IDateTime"] = new() { Type = JsonSchemaType.String, Format = "date-time" },
            ["IDayOfWeek"] = new() { Type = JsonSchemaType.Integer },
            // INumber<T> — ASP.NET Core OpenAPI concatenates the base name with the CLR type-argument name
            ["INumberByte"] = new() { Type = JsonSchemaType.Integer, Format = "int32" },
            ["INumberSByte"] = new() { Type = JsonSchemaType.Integer, Format = "int32" },
            ["INumberInt16"] = new() { Type = JsonSchemaType.Integer, Format = "int32" },
            ["INumberUInt16"] = new() { Type = JsonSchemaType.Integer, Format = "int32" },
            ["INumberInt32"] = new() { Type = JsonSchemaType.Integer, Format = "int32" },
            ["INumberUInt32"] = new() { Type = JsonSchemaType.Integer, Format = "int64" },
            ["INumberInt64"] = new() { Type = JsonSchemaType.Integer, Format = "int64" },
            ["INumberUInt64"] = new() { Type = JsonSchemaType.Integer, Format = "int64" },
            ["INumberSingle"] = new() { Type = JsonSchemaType.Number, Format = "float" },
            ["INumberDouble"] = new() { Type = JsonSchemaType.Number, Format = "double" },
            ["INumberDecimal"] = new()
            {
                Type = JsonSchemaType.Number,
                Format = "double",
            },
            ["INumberIntPtr"] = new() { Type = JsonSchemaType.Integer, Format = "int64" },
            ["INumberUIntPtr"] = new()
            {
                Type = JsonSchemaType.Integer,
                Format = "int64",
            },
        };

    public Task TransformAsync(
        OpenApiDocument document,
        OpenApiDocumentTransformerContext context,
        CancellationToken cancellationToken
    )
    {
        if (document.Components?.Schemas is not { } schemas)
        {
            return Task.CompletedTask;
        }

        foreach ((string name, OpenApiSchema nativeSchema) in PrimitiveSchemas)
        {
            if (schemas.ContainsKey(name))
            {
                schemas[name] = nativeSchema;
            }
        }

        return Task.CompletedTask;
    }
}
